Allow specifying localhost and container ports for port-forward
abrochard/kubel pull request #39
Opened 2020-11-09 22:12 UTC by slcourchesne

For kubel-port-forward-pod, accept a string instead of a number to be able to specify "local:container" ports instead of having the same for both.

2020-11-10 22:51 UTC, abrochard requested changes
Thank you for this! It's a great feature. Left a comment regarding the docstring that also needs to be updated please.

2020-11-10 22:51 UTC, abrochard commented on kubel.el
>  P is the port as integer."
could you also update the doc please?

2020-11-11 02:11 UTC, slcourchesne commented on kubel.el
>  P is the port as integer."
Adjusted.

2020-11-11 15:34 UTC, abrochard approved these changes
Awesome, thank you!

2020-11-11 15:34 UTC, merged